/**
 * TMSI Equipment Price Listing
 * Copyright (c) 2026 Pedro Alexandre. All rights reserved.
 * PROPRIETARY AND CONFIDENTIAL — unauthorised use, copying, modification or
 * distribution is strictly prohibited. See LICENSE at the repository root.
 */

import { NextRequest, NextResponse } from 'next/server';
import { createSupabaseServerClient } from '@/lib/supabase-server';
import { buildXlsx } from '@/lib/xlsx-export';
import { alertaDe } from '@/lib/alert';
import { getPriceNotice } from '@/lib/price-notice';
import { getMe } from '@/lib/me';
import { getBranding, getBrandingLogoBuffer, footerLines, slugify } from '@/lib/branding';

type BranchPriceRow = {
  product_id: string;
  name: string;
  category_id: string | null;
  status: string;
  item_type: string;
  branch_id: string;
  currency: string;
  total_cost_eur: number | null;
  margin: number | null;
  min_price: number | null;
  ref_price: number | null;
  alert: string | null;
  scope_type: string | null;
};

type SellingPriceRow = {
  product_id: string;
  name: string;
  branch_id: string;
  currency: string;
  min_price: number | null;
  ref_price: number | null;
  lead_time_days: number | null;
  category_id: string | null;
};

// ⚠️11: "All branches" é o que o filtro diz, não o que o ficheiro traz — sem
// filtro, ambas as vistas incluem também as linhas de canal. O rótulo passa a
// descrever o conteúdo.
//
// item 68 (2026-09-23): a primeira versão decidia isto por `scope_type`, que
// existe em `v_branch_prices` mas **NÃO** em `v_selling_prices` — o ramo dos
// papéis sem custos pedia uma coluna inexistente e a rota inteira devolvia
// `column v_selling_prices.scope_type does not exist`. O sinal passa a ser o
// mesmo que o ecrã /prices já usa: uma linha é de canal quando o seu
// `branch_id` é o id de um canal. Serve as duas vistas sem depender de uma
// coluna que só uma delas projecta.
function scopeLabel(branch: string | null, temLinhasDeCanal: boolean) {
  if (branch) return branch;
  return temLinhasDeCanal ? 'All branches and channels' : 'All branches';
}

// Os canais que o utilizador vê — a RLS de `tmsi.channels` já limita ao que
// lhe pertence, e é a mesma leitura que o ecrã /prices faz.
async function channelIds(
  supabase: Awaited<ReturnType<typeof createSupabaseServerClient>>,
): Promise<Set<string>> {
  const { data } = await supabase.schema('tmsi').from('channels').select('id');
  return new Set((data ?? []).map((c: { id: string }) => c.id));
}

// "Generated by" leva o NOME de quem gerou, nunca o email (decisão do Pedro,
// 2026-09-23): o ficheiro circula fora da empresa e o endereço de uma pessoa
// não tem de viajar com uma lista de preços. Desde a 0021 o nome vem de
// `tmsi.me()` — o mesmo pedido que decide a vista —, e não de um `profiles`
// à parte.

function respond(buffer: Uint8Array, filename: string) {
  // `as unknown as BodyInit`: see products/export/route.ts's identical comment —
  // a type-checker/lib mismatch in this project's pinned TypeScript
  // 7.0.2, not a runtime problem (Uint8Array is a spec-valid body).
  return new NextResponse(buffer as unknown as BodyInit, {
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  });
}

// i10: exact same view/column choice as /prices — never a query that
// reaches further than what that page's screen already shows. `branch`
// scopes rows on top of whatever the view already returned; it never
// picks the view or reaches past RLS (a sales/agent request for another
// branch, or for the cost view, just gets 0 rows for that branch — the
// query param carries no authority of its own).
//
// The two roles' fetches are two fully separate, literal `.from()`/
// `.select()` calls (not one dynamic viewName/columns string branched
// afterwards) — matching how every other page in this codebase queries
// Postgrest, and avoiding a dynamic select-string union that postgrest-js's
// return-type inference doesn't resolve cleanly.
//
// `.overrideTypes()` goes LAST, after the conditional `.eq()` — the exact
// bug this project already found once (docs/STATE.md, E3-i6 F1, in
// audit/page.tsx): postgrest-js narrows to a filter-less builder type
// once you cross into a "transform" stage, so a filter chained (or
// reassigned) afterwards doesn't type-check. Filters always before that
// narrowing call, never after.
export async function GET(request: NextRequest) {
  const branch = request.nextUrl.searchParams.get('branch');
  const supabase = await createSupabaseServerClient();

  // 0021: uma chamada dá a identidade, o direito a custos e o nome de quem
  // gera — eram getUser() + can_read_costs() + profiles. Sem identidade, 401.
  const me = await getMe(supabase);
  if (!me) {
    return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
  }
  const canReadCosts = me.can_read_costs === true;
  const generatedAt = new Date();
  const [branding, aviso] = await Promise.all([getBranding(), getPriceNotice()]);
  const logo = await getBrandingLogoBuffer(branding.logoId);
  // Item 32: o aviso de preços operacionais abre o rodapé, nos dois ramos.
  const rodape = [...(aviso ? [aviso] : []), ...footerLines(branding)];
  const filename = `${slugify(branding.displayName)}-prices-${branch ?? 'all'}-${generatedAt.toISOString().slice(0, 10)}.xlsx`;

  // Desde a 0021 as duas vistas trazem nome, categoria, estado e tipo — o
  // export deixou de cruzar com o catálogo em memória.
  const ORDEM_AMBITO = ['SA', 'TBM', 'CORP', 'LTD'];
  const pesoAmbito = (id: string) => {
    const i = ORDEM_AMBITO.indexOf(id);
    return i === -1 ? ORDEM_AMBITO.length : i;
  };

  if (canReadCosts) {
    let query = supabase
      .schema('tmsi')
      .from('v_branch_prices')
      .select('product_id, name, category_id, status, item_type, branch_id, scope_type, currency, total_cost_eur, margin, min_price, ref_price, alert')
      // ⚠️11: sem ORDER BY, v_branch_prices (UNION ALL) devolvia as linhas de
      // canal num bloco no fim do ficheiro, a ~150 linhas do artigo a que
      // pertencem — quem lê o bloco de um artigo via 4 âmbitos e concluía que
      // o 5.º não existia. Ordenar por artigo põe cada âmbito ao lado do seu.
      .order('product_id')
      .order('branch_id');
    if (branch) {
      query = query.eq('branch_id', branch);
    }
    const { data: rows, error } = await query.overrideTypes<BranchPriceRow[], { merge: false }>();
    if (error) {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }
    // Ordem de apresentação: categoria -> código -> âmbito (ordem comercial
    // das filiais, canais no fim). O ORDER BY do PostgREST já garante
    // determinismo; esta ordenação é a que a folha do Excel usa.
    const ordenadas = [...rows].sort(
      (a, b) =>
        (a.category_id ?? '\uffff').localeCompare(b.category_id ?? '\uffff') ||
        a.product_id.localeCompare(b.product_id) ||
        pesoAmbito(a.branch_id) - pesoAmbito(b.branch_id) ||
        a.branch_id.localeCompare(b.branch_id),
    );

    const currencies = [...new Set(rows.map((r) => r.currency))].sort();
    const buffer = await buildXlsx({
      sheetTitle: 'Price list',
      reportTitle: `${branding.displayName} — Price list`,
      scope: scopeLabel(branch, rows.some((r) => r.scope_type === 'channel')),
      currency: currencies.join(', ') || '—',
      generatedBy: me.full_name ?? '—',
      generatedAt,
      headers: ['Code', 'Product', 'Scope', 'Status', 'Currency', 'Total cost (EUR)', 'Margin', 'Min price', 'Ref price', 'Alert'],
      widths: [12, 34, 10, 10, 10, 16, 10, 12, 12, 20],
      // Total cost e preços a duas casas; margem em percentagem. Vão como
      // NÚMEROS com formato, não como texto: quem receber tem de poder somar.
      numberFormats: { 5: '0.00', 6: '0.0%', 7: '0.00', 8: '0.00' },
      rows: ordenadas.map((r) => [
        r.product_id,
        r.name,
        r.branch_id,
        r.status,
        r.currency,
        r.total_cost_eur,
        r.margin,
        r.min_price,
        r.ref_price,
        // item 67: serviços e opções não são classificados — célula vazia.
        // O ramo SEM custos (abaixo) nunca teve a coluna Alert: a margem não
        // circula fora dos papéis de custos.
        alertaDe(r.alert, r.item_type),
      ]),
      footerLines: rodape,
      primaryColor: branding.primaryColor,
      fontFamily: branding.fontFamily,
      logo,
    });
    return respond(buffer, filename);
  }

  let query = supabase
    .schema('tmsi')
    .from('v_selling_prices')
    .select('product_id, name, category_id, branch_id, currency, min_price, ref_price, lead_time_days')
    .order('product_id')
    .order('branch_id');
  if (branch) {
    query = query.eq('branch_id', branch);
  }
  const { data: rows, error } = await query.overrideTypes<SellingPriceRow[], { merge: false }>();
  if (error) {
    return NextResponse.json({ error: error.message }, { status: 400 });
  }

  const canais = await channelIds(supabase);
  const ordenadas = [...rows].sort(
    (a, b) =>
      (a.category_id ?? '\uffff').localeCompare(b.category_id ?? '\uffff') ||
      a.product_id.localeCompare(b.product_id) ||
      pesoAmbito(a.branch_id) - pesoAmbito(b.branch_id) ||
      a.branch_id.localeCompare(b.branch_id),
  );
  const currencies = [...new Set(rows.map((r) => r.currency))].sort();
  const buffer = await buildXlsx({
    sheetTitle: 'Price list',
    reportTitle: `${branding.displayName} — Price list`,
    scope: scopeLabel(branch, rows.some((r) => canais.has(r.branch_id))),
    currency: currencies.join(', ') || '—',
    generatedBy: me.full_name ?? '—',
    generatedAt,
    headers: ['Code', 'Product', 'Scope', 'Currency', 'Min price', 'Ref price', 'Lead time (days)'],
    widths: [12, 34, 10, 10, 12, 12, 16],
    numberFormats: { 4: '0.00', 5: '0.00' },
    rows: ordenadas.map((r) => [
      r.product_id,
      r.name,
      r.branch_id,
      r.currency,
      r.min_price,
      r.ref_price,
      r.lead_time_days,
    ]),
    footerLines: rodape,
    primaryColor: branding.primaryColor,
    fontFamily: branding.fontFamily,
    logo,
  });
  return respond(buffer, filename);
}
